
title: {{ appName }} # You can change the title to something user friendly.
description: This is my website.
runConfig:
  default:
    host: '127.0.0.1'
    port: 8000
  open:
    host: '0.0.0.0'
    port: 80
db:
  main:
    type: nedb
    path: db
adminUser:
  username: admin
  password: "{{ adminPass }}"
secret: "{{ token }}"
emailInterface:
  app: carolina/lib/email/terminal-email
  from: carolina_webmaster@example.com
apps:
  common: # Do not change this name or remove this app
    app: carolina/apps/common
  carolinaAuthenticationApp: # Do not remove this app, but you can change its data options
    app: carolina/apps/auth
    mount: 'auth'
    db: main
    data: # You can edit the values in this section
      emailVerificationSubject: E-Mail Verification
      emailVerificationText: "Your confirmation code is:"
      passwordResetSubject: Password Reset
      passwordResetText: "Your new password is:"
  carolinaStarterApp: # You may remove this app and replace it with your home page
    app: carolina/apps/starter
    mount: ''
    db: main
    data:
      bootswatchTheme: minty
      enterButtonText: ENTER
      link: /main
      title: "{{ appName }}"
      welcomeMessage: Welcome to {{ appName }}.
