
title: My Carolina Site
description: This is my website.
databases:
  main:
    type: nedb
    dataDir: db
apps:
  - app: carolina/apps/starter
    mount: ''
adminUser:
  username: admin
  password: {{ adminPass }}
token: {{ token }}