
title: {{ appName }}
description: This is my website.
runConfig:
  default:
    host: localhost
    port: 8888
  open:
    host: '0.0.0.0'
    port: 80
db:
  main:
    type: nedb
    path: db
adminUser:
  username: admin
  password: "{{ adminPass }}"
secret: "{{ token }}"
apps:
  - app: carolina/apps/starter
    mount: ''
    db: main
    data:
      enterButtonText: ENTER
      welcomeMessage: Welcome to {{ appName }}.
