
title: {{ appName }}
description: This is my website.
runConfig:
  default:
    host: localhost
    port: 8888
  open:
    host: '0.0.0.0'
    port: 80
db:
  main:
    type: nedb
    path: db
adminUser:
  username: admin
  password: "{{ adminPass }}"
secret: "{{ token }}"
apps:
  common: # Do not change this name or remove this app
    app: carolina/apps/common_static
  carolinaAuthenticationApp:
    app: carolina/apps/auth
    mount: 'auth'
    db: main
    data: null
  carolinaStarterApp:
    app: carolina/apps/starter
    mount: ''
    db: main
    data:
      bootswatchTheme: minty
      enterButtonText: ENTER
      link: /main
      title: "{{ appName }}"
      welcomeMessage: Welcome to {{ appName }}.
