
title: {{ appName }} # You can change the title to something user friendly.
description: This is my website.
runConfig:
  default:
    host: '127.0.0.1'
    port: 8000
  open:
    host: '0.0.0.0'
    port: 80
db:
  main:
    type: nedb
    path: db
adminUser:
  username: admin
  password: "{{ adminPass }}"
secrets:
  clientSideSalt: {{ salt0 }}
  salt1: {{ salt1 }}
  salt2: {{ salt2 }}
  salt3: {{ salt3 }}
  salt4: {{ salt4 }}
  salt5: {{ salt5 }}
  salt6: {{ salt6 }}
  salt7: {{ salt7 }}
  salt8: {{ salt8 }}
siteMenu:
  - link: '/main'
    title: Home
  - link: '/auth'
    title: Account
  - link: '/admin'
    title: Admin Panel
emailInterface:
  app: carolina/lib/email/terminal-email
  from: carolina_webmaster@example.com
apps:
  common: # Do not change this name or remove this app
    app: carolina/apps/common
  carolinaAuthenticationApp: # Do not remove this app, but you can change its data options
    app: carolina/apps/auth
    mount: 'auth'
    db: main
    data: # You can edit the values in this section
      emailVerificationSubject: E-Mail Verification
      emailVerificationText: "Your confirmation code is:"
      passwordResetSubject: Password Reset
      passwordResetText: "Your new password is:"
  carolinaAdminApp:
    app: carolina/apps/admin
    mount: 'admin'
    db: main
  carolinaStarterApp: # You may remove this app and replace it with your home page
    app: carolina/apps/starter
    mount: ''
    db: main
    data:
      bootswatchTheme: minty
      enterButtonText: ENTER
      link: /main
      title: "{{ appName }}"
      welcomeMessage: Welcome to {{ appName }}.
