
title: {{ appName }}
description: This is my website.
db:
  main:
    type: nedb
    path: db
adminUser:
  username: admin
  password: "{{ adminPass }}"
secret: "{{ token }}"
apps:
  - app: carolina/apps/starter
    mount: ''
    db: main
    data:
      enterButtonText: ENTER
      welcomeMessage: Welcome to {{ appName }}.
