
title: My Carolina Site
description: This is my website.
db:
  main:
    type: nedb
    path: db
apps:
  - app: carolina/apps/starter
    mount: ''
adminUser:
  username: admin
  password: {{ adminPass }}
secret: {{ token }}