
title: {{ appName }}
description: This is my website.
runConfig:
  default:
    host: '127.0.0.1'
    port: 8000
  open:
    host: '0.0.0.0'
    port: 80
db:
  main:
    type: nedb
    path: db
adminUser:
  username: admin
  password: "{{ adminPass }}"
secret: "{{ token }}"
emailInterface:
  app: carolina/lib/email/terminal-email
  from: carolina_webmaster@example.com
apps:
  common: # Do not change this name or remove this app
    app: carolina/apps/common
  carolinaAuthenticationApp:
    app: carolina/apps/auth
    mount: 'auth'
    db: main
    data:
      emailVerificationSubject: E-Mail Verification
      emailVerificationText: Click the link below to confirm your e-mail address.
  carolinaStarterApp:
    app: carolina/apps/starter
    mount: ''
    db: main
    data:
      bootswatchTheme: minty
      enterButtonText: ENTER
      link: /main
      title: "{{ appName }}"
      welcomeMessage: Welcome to {{ appName }}.
